[package]
description = "proc-macro crate for hala pprof"
documentation = "https://docs.rs/hala-pprof-derive"
edition.workspace = true
license = "MIT"
name = "hala-pprof-derive"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = {workspace = true}
syn = {workspace = true}
uuid = {workspace = true}

[lib]
proc-macro = true

[toolchain]
channel = "nightly"
