[package]
description = "High Performance network service engine"
documentation = "https://docs.rs/rgnix"
edition.workspace = true
license = "MIT"
name = "rgnix"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = {workspace = true}
dashmap = {workspace = true}
futures = {workspace = true}
hala-rs = {workspace = true}
multiaddr = {workspace = true}
thiserror = {workspace = true}
uuid = {workspace = true}
