[package]
description = "high-performance network architecture for general purpose server-side rust application"
documentation = "https://docs.rs/hala-retty"
edition.workspace = true
license = "MIT"
name = "hala-retty"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = {workspace = true}
dashmap = {workspace = true}
futures = {workspace = true}
hala-rs = {workspace = true}
multiaddr = {workspace = true}
thiserror = {workspace = true}
uuid = {workspace = true}
