[package]
edition.workspace = true
name = "rgnix"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {workspace = true}
duration-str = {workspace = true}
hala-rs = {workspace = true}
log = {workspace = true}

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemalloc-ctl = {workspace = true}
tikv-jemallocator = {workspace = true, features = ["profiling"]}
