[tasks.test]
dependencies = [
  "single-thread-test",
  "multi-thread-test",
]

[tasks.single-thread-test]
args = ["test", "--no-default-features", "--features", "single-thread"]
command = "cargo"

[tasks.multi-thread-test]
args = ["test"]
command = "cargo"
