[package]
description = "The rust reverse proxy framework for hala os"
documentation = "https://docs.rs/hala-rproxy"
edition.workspace = true
license = "MIT"
name = "hala-rproxy"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
