[package]
description = "Hala rproxy framework."
documentation = "https://docs.rs/hala-rproxy"
edition.workspace = true
license = "MIT"
name = "hala-rproxy"
repository.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hala-future = {workspace = true}
hala-io = {workspace = true}
hala-lockfree = {workspace = true}
hala-quic = {workspace = true}
hala-sync = {workspace = true}
hala-tcp = {workspace = true}
hala-tls = {workspace = true}

async-trait = {workspace = true}
bytes = {workspace = true}
clap = {workspace = true}
dashmap = {workspace = true}
futures = {workspace = true}
log = {workspace = true}
uuid = {workspace = true, features = ["v4", "fast-rng", "macro-diagnostics"]}

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemalloc-ctl = {workspace = true}
tikv-jemallocator = {workspace = true, features = ["profiling"]}

[dev-dependencies]
divan = {workspace = true}
hala-io = {workspace = true, features = ["mio-driver"]}
hala-test = {workspace = true}
pretty_env_logger = {workspace = true}
