[package]
description = "Hala asynchronous network programming primitive type udp"
documentation = "https://docs.rs/hala-tcp"
edition.workspace = true
license = "MIT"
name = "hala-tcp"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {workspace = true}
hala-future = {workspace = true}
hala-io = {workspace = true}
log = {workspace = true}
thiserror = {workspace = true}

[dev-dependencies]
divan = {workspace = true}
futures-test = {workspace = true}
hala-test = {workspace = true}
pretty_env_logger = {workspace = true}
rand = {workspace = true}

[features]
