[package]
description = "Hala http protocol implementation."
documentation = "https://docs.rs/hala-http"
edition.workspace = true
license = "MIT"
name = "hala-http"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
http = { workspace = true }
httparse = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

hala-future = { workspace = true }
hala-io = { workspace = true }
hala-tcp = { workspace = true }
hala-tls = { workspace = true }

[dev-dependencies]
hala-test = { workspace = true }
pretty_env_logger = { workspace = true }
hala-io = { workspace = true, features = ["mio-driver"] }


[features]
default = ["json"]
json = ["serde", "serde_json"]
