[package]
description = "Hala http protocol implementation."
documentation = "https://docs.rs/hala-http"
edition.workspace = true
license = "MIT"
name = "hala-http"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
