[package]
description = "quic tunnel framework base on rgnix."
documentation = "https://docs.rs/quictun"
edition.workspace = true
license = "MIT"
name = "quictun"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {workspace = true}
hala-rs = {workspace = true}
log = {workspace = true}
rgnix = {workspace = true}
uuid = {workspace = true}
