[package]
description = "Hala rproxy framework."
documentation = "https://docs.rs/hala-rproxy2"
edition.workspace = true
license = "MIT"
name = "hala-rproxy2"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = {workspace = true}
dashmap = {workspace = true}
futures = {workspace = true}
hala-rs = {workspace = true}
thiserror = {workspace = true}
uuid = {workspace = true}
