[package]
description = "A structured logging facade for rust programming."
documentation = "https://docs.rs/hala-tracing"
edition.workspace = true
license = "MIT"
name = "hala-tracing"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = {workspace = true}
dashmap = {workspace = true}
log = {workspace = true}
serde = {workspace = true}
uuid = {workspace = true}
