[package]
description = "Event tracing for rust"
documentation = "https://docs.rs/hala-tracing"
edition.workspace = true
license = "MIT"
name = "hala-tracing"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = {workspace = true}
dashmap = {workspace = true}
hala-tracing-derive = {workspace = true}

serde = {workspace = true}
uuid = {workspace = true}

[dev-dependencies]
divan = {workspace = true}
log = {workspace = true}

[[bench]]
harness = false
name = "tracing"

[[bench]]
harness = false
name = "log"
